### PR TITLE
Add support for querying an existing cluster

### PR DESCRIPTION
**Pull request by markgoddard**
The cluster_state variable can now take a third value - 'query'.

I added this during the EoD slurm deployment. It's on the group-resources-wip branch, but thought it could be merged separately.

### CODE REVIEW

**Comment by markgoddard** [comment]
Thoughts?

**Comment by gadamiak** [comment]
Sounds good!

**Comment by markgoddard** [comment]
In that case we'd execute `openstack stack output show <non existent stack>`, which would fail.

**Comment by markgoddard** [comment]
?

**Comment by markgoddard** [comment]
Oh yeah, thanks!

**Pull request merged**
